sudo: required

language: cpp
compiler: gcc
dist: trusty

before_install:
        - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
install:
        - sudo apt-get install -y pkg-config libx11-dev
script:
        - BUILD_VST2=true BUILD_LV2=true BUILD_JACK=true make
